---
deployment:
  tasks:
    - export DEPLOYPATH=/home/green64
#this variant below is working well
#    - /bin/cp  public_html/index.php $DEPLOYPATH

#this code is for deploying all forder
     -/bin/cp -R public_html $DEPLOYPATH
